### ISSUE TITLE
Consider splitting into two starters for web API and storage

### ISSUE THREAD

**Issue by rhys-saldanha** [mihaita-tinta/webauthn-spring-boot-starter#26]
Whilst I really like this starter, and want to use it in my projects, I already have an existing database table for storing users. 

Would you consider splitting this starter into a `webauthn-spring-boot-starter-web` and `webauthn-spring-boot-starter-jpa`, where the latter is optional and a developer can choose to instead provide spring beans of some interface or interfaces for user storage and retrieval?

**Comment by mihaita-tinta** [comment]
Hi. Thanks for your proposal. It can simplify things a lot. With this initial approach you would have to link users between your tables and what the library stores.

Can you try to add your own `WebAuthnUserRepository` and `WebAuthnCredentialsRepository` (primary) beans? There are however quite a few methods you need to implement.

**Comment by mihaita-tinta** [comment]
I added the library [on this branch](https://github.com/mihaita-tinta/webauthn-spring-boot-starter/tree/users/mihaita.tinta/split-jpa). The jpa starter is [here](https://github.com/mihaita-tinta/webauthn-spring-boot-starter-jpa) and two working examples [webauthn starter + jpa](https://github.com/mihaita-tinta/webauthn-spring-boot-starter-demo/tree/users/mihaita.tinta/split-jpa) and [webauthn starter + in memory](https://github.com/mihaita-tinta/webauthn-spring-boot-starter-demo/tree/in-memory). I will test this a little more and once I'm done I will update everything to 0.2.0-RELEASE. If you have any feedback on the changes just let me know.

**Comment by mihaita-tinta** [comment]
You can also add other user/credentials repos. The library has a conditional hint and [if you define one](https://github.com/mihaita-tinta/webauthn-spring-boot-starter-demo/blob/cd5c46eaaf83baf95d51bf04b3a49fe70bab03bf/src/main/java/com/mih/webauthn/demo/SecurityConfig.java#L91) you should be able to use it.

**Comment by mihaita-tinta** [comment]
@rhys-saldanha I will close the issue. If you have any questions/feebdack about this update you can reopen the issue. Thanks.
